### ISSUE TITLE
how can i build a release configuration in Windows?

### ISSUE THREAD

**Issue by tristanbarcelon** [microsoft/lagscope#35]
I've tried editing the do-cmake.bat to pass in -DCMAKE_BUILD_TYPE=Release when creating the build or --target Release in conjunction with the --build parameter but in either scenarios, it's creating a debug build which requires VCRUNTIME140D.dll. From what I've gathered, this DLL cannot be redistributed. Where can I find a release build so I only need to install the publicly available vcredist to run lagscope.exe for Windows?

**Comment by santoshx** [comment]
@tristanbarcelon

I'm not immediately sure how to do cmake release build.  Can you meanwhile ignore this cmake build and remove src/CMakeLists.txt do normal visual studio release build?

Visual studio -> File -> New -> Project from existing sources.

**Comment by tristanbarcelon** [comment]
Actually, that didn't work. What did work was opening Visual Studio -> Open -> Folder and selecting the the src folder. By default it creates a debug build in folder in c:\users\<username>\CMakeBuilds\<guid>\build\x64-Debug (default). You could then change configuration from x64-Debug to x64-Release. This will create another build subfolder called x64-Release. Right click on CMakeLists.txt after switching configuration and select Build lagscope.exe.

My folder structure looks like this.

![image](https://user-images.githubusercontent.com/5810165/80265952-715e9980-8667-11ea-8f4a-69c0d3812b07.png)

Thank you for your help!
