### ISSUE TITLE
lagscope running on Windows reports negative min value

### ISSUE THREAD

**Issue by wilsonNg007** [microsoft/lagscope#40]
Running lagscope sending from one windows host machine to a remote windows host machine with below lagscope cmd, and the min value reports negative value, which appears affecting the average value calculation.
[winHost_lagscope_rawdata_1Mpings_ErrorNegativeMinValue_run0.csv](https://github.com/microsoft/lagscope/files/6525561/winHost_lagscope_rawdata_1Mpings_ErrorNegativeMinValue_run0.csv)

Looking from the attached rawdata csv file, there is one ping (out of 1M) which report a huge latency value, which seems to be messing up the calculation.   

Index	 Latency(us)
437555	2450296064

--------------------------

c:\Users\wilson\Downloads\Tools>lagscope.exe -s192.168.1.4 -H -a100 -l250 -c98 -RwinHost_lagscope_rawdata_run0.csv
[winHost_lagscope_rawdata_1Mpings_ErrorNegativeMinValue_run0.csv](https://github.com/microsoft/lagscope/files/6525563/winHost_lagscope_rawdata_1Mpings_ErrorNegativeMinValue_run0.csv)

lagscope 1.0.0
---------------------------------------------------------
16:04:28 INFO: New connection: local:25001 [socket:232] --> 192.168.1.4:6001
16:56:19 INFO: TEST COMPLETED.
16:56:19 INFO: Ping statistics for 192.168.1.4:
16:56:19 INFO:    Number of successful Pings: 1000000
16:56:19 INFO:    Minimum = -1844671232.470us, Maximum = 206354.400us, Average = 1246.071us
16:56:19 INFO: Dumping all latencies into csv file: winHost_lagscope_rawdata_run0.csv

**Comment by wilsonNg007** [comment]
If I exclude that one huge value (2450296064) and calculate the average with the rest of values, it's 3090.295188us, which seems to be reasonable and coincide with another lagscope measurement result with 100K pings.

**Comment by wilsonNg007** [comment]
I re-ran lagscope again (with default 1M pings) and it's again reporting the same error.  

[winHost_lagscope_rawdata_1Mpings_ErrorNegativeMinAndAvgValue_run1.csv](https://github.com/microsoft/lagscope/files/6525661/winHost_lagscope_rawdata_1Mpings_ErrorNegativeMinAndAvgValue_run1.csv)

The raw data csv file reports two huge latency value.  Excluding them and the average becomes 3119.540642us

Index | Latency(us)
823301 | 2450295967
232152 | 2450295938

c:\Users\wilson\Downloads\Tools>lagscope.exe -s192.168.1.4 -H -a100 -l250 -c98 -RwinHost_lagscope_rawdata_1Mpings_run1.csv
lagscope 1.0.0
---------------------------------------------------------
17:47:00 INFO: New connection: local:25001 [socket:232] --> 192.168.1.4:6001
18:39:21 INFO: TEST COMPLETED.
18:39:21 INFO: Ping statistics for 192.168.1.4:
18:39:21 INFO:    Number of successful Pings: 1000000
18:39:21 INFO:    Minimum = -1844671358.570us, Maximum = 210940.400us, Average = -569.358us
18:39:21 INFO: Dumping all latencies into csv file: winHost_lagscope_rawdata_1Mpings_run1.csv

**Comment by santoshx** [comment]
I can also repro this. I used these simple commands on same Windows VM.
>lagscope.exe -r
>lagscope.exe -s

Function time_in_nanosec defined in win_utils.c is rarely returning negative value leading to negative latency.

**Comment by santoshx** [comment]
@wilsonNg007  Can you please try to repro this issue with branch users/sayadawa/fix1? This branch has a possible fix.

**Comment by wilsonNg007** [comment]
@santoshx , could you provide me a binary for this fix?  Thanks.

**Comment by santoshx** [comment]
> @santoshx , could you provide me a binary for this fix? Thanks.

Here it is https://github.com/santoshx/temp/raw/master/lagscope.exe

**Comment by santoshx** [comment]
Fixed by https://github.com/microsoft/lagscope/pull/43
